Repository ShimilSAbraham/Hacktoberfest-2021, pull requests merged in 2021-10, with the labels that each got.

#3 card update
  index.html
Labels: hacktoberfest-accepted

#1 Update index.html
  index.html
Labels: hacktoberfest-accepted

#2 Update index.html
  index.html
Labels: hacktoberfest-accepted

#4 Added Card for HariketSheth
  index.html
Labels: hacktoberfest-accepted

#5 Update index.html
  index.html
Labels: hacktoberfest-accepted

#6 Added my card
  index.html
Labels: hacktoberfest-accepted

#11 Add Patricio Díaz avatar
  .vscode/settings.json
  index.html
Labels: hacktoberfest-accepted

#12 Update index.html
  index.html
Labels: hacktoberfest-accepted

#14 add name
  index.html
Labels: hacktoberfest-accepted

#15 Add "Muhammad Gimnastiar" card
  index.html
Labels: hacktoberfest-accepted

#16 Made changes to index.html
  index.html
Labels: hacktoberfest-accepted

#17 Update index.html
  index.html
Labels: hacktoberfest-accepted

#18 index.html
  index.html
Labels: hacktoberfest-accepted

#19 Added a card for Sahil Kumar
  index.html
Labels: hacktoberfest-accepted

#21 Update index.html
  index.html
Labels: hacktoberfest-accepted

#22 updated card on index.html
  index.html
Labels: hacktoberfest-accepted

#25 Added my profile card in the page.
  index.html
Labels: hacktoberfest-accepted

#26 Updated index.html
  index.html
Labels: hacktoberfest-accepted

#27 Updated the index.html
  index.html
Labels: hacktoberfest-accepted

#32 Updated index.html
  index.html
Labels: hacktoberfest-accepted

#35 Update index.html
  index.html
Labels: hacktoberfest-accepted

#37 Updated index.html with my card
  index.html
Labels: hacktoberfest-accepted

#39 index.html edited
  index.html
Labels: hacktoberfest-accepted

#40 Added Self Card : ( Triparno Chatterjee )
  index.html
Labels: hacktoberfest-accepted

#41 edit index.html
  index.html
Labels: hacktoberfest-accepted

#42 Added pasindujr
  index.html
Labels: hacktoberfest-accepted

#44 Update index.html
  index.html
Labels: hacktoberfest-accepted

#43 Please check out my code...
  index.html
Labels: hacktoberfest-accepted

#47 Update index.html
  index.html
Labels: hacktoberfest-accepted

#48 Update index.html
  index.html
Labels: hacktoberfest-accepted

#49 added my profile details !
  index.html
Labels: hacktoberfest-accepted

#50 Update index.html
  index.html
Labels: hacktoberfest-accepted

#51 Update Index.html added my Profile on that.
  index.html
Labels: hacktoberfest-accepted

#52 add my profile
  index.html
Labels: hacktoberfest-accepted

#53 Update index.html
  index.html
Labels: hacktoberfest-accepted

#54 Updated and added a new card for my profile
  index.html
Labels: hacktoberfest-accepted

#55 Updated index.html
  index.html
Labels: hacktoberfest-accepted

#56 adding card
  index.html
Labels: hacktoberfest-accepted

#57 Update index.html
  index.html
Labels: hacktoberfest-accepted

#58 Update index.html
  index.html
Labels: hacktoberfest-accepted

#60 added my profile card
  index.html
Labels: hacktoberfest-accepted

#61 Please review my PR
  index.html
Labels: hacktoberfest-accepted

#62 added info
  index.html
Labels: hacktoberfest-accepted

#63 Added My Profile Card
  index.html
Labels: hacktoberfest-accepted

#78 Card added
  index.html
Labels: hacktoberfest-accepted

#73 new card
  index.html
Labels: hacktoberfest-accepted

#67 Update index.html
  index.html
Labels: hacktoberfest-accepted

#68 Added my card
  index.html
Labels: hacktoberfest-accepted

#70 Updated index.html
  index.html
Labels: hacktoberfest-accepted

#71 Added my GitHub profile (card)
  index.html
Labels: hacktoberfest-accepted

#72 update index.html with my card
  index.html
Labels: hacktoberfest-accepted

#74 Added my card
  index.html
Labels: hacktoberfest-accepted

#75 added my card
  index.html
Labels: hacktoberfest-accepted

#77 added my card
  index.html
Labels: hacktoberfest-accepted

#79 Update index.html
  index.html
Labels: hacktoberfest-accepted

#80 added my card
  index.html
Labels: hacktoberfest-accepted

#81 Update index.html
  index.html
Labels: hacktoberfest-accepted

#82 Updated index.html
  index.html
Labels: hacktoberfest-accepted

#83 Added a card and connected my profile picture and profile
  index.html
Labels: hacktoberfest-accepted

#84 added card in home page
  index.html
Labels: hacktoberfest-accepted

#85 Updated in index.html (added a card)
  index.html
Labels: hacktoberfest-accepted

#86 Added card for fatimareefat
  index.html
Labels: hacktoberfest-accepted

#87 Update index.html
  index.html
Labels: hacktoberfest-accepted

#88 Added my Profile Info
  index.html
Labels: hacktoberfest-accepted

#89 adding my card
  index.html
Labels: hacktoberfest-accepted

#90 added my card
  index.html
Labels: hacktoberfest-accepted

#91 ⭐Update in index.html⭐
  index.html
Labels: hacktoberfest-accepted

#92 Added my card
  index.html
Labels: hacktoberfest-accepted

#93 Update index.html
  index.html
Labels: hacktoberfest-accepted

#94 Added my card and reformat the code
  index.html
Labels: hacktoberfest-accepted

#95 Update index.html
  index.html
Labels: hacktoberfest-accepted

#96 Added my card and made the code beautiful!
  index.html
Labels: hacktoberfest-accepted

#97 Update index.html
  index.html
Labels: hacktoberfest-accepted

#98 Add card for my profile
  index.html
Labels: hacktoberfest-accepted

#99 Update index.html
  index.html
Labels: hacktoberfest-accepted

#101 Update index.html
  index.html
Labels: hacktoberfest-accepted

#102 Update index.html
  index.html
Labels: hacktoberfest-accepted

#103 Updated index.html as per Instrunctions
  index.html
Labels: hacktoberfest-accepted

#105 Hrushi
  index.html
Labels: hacktoberfest-accepted

#106 Updated index.html
  index.html
Labels: hacktoberfest-accepted

#108 Update index.html
  index.html
Labels: hacktoberfest-accepted

#109 updated index.html
  index.html
Labels: hacktoberfest-accepted

#110 Update index.html
  index.html
Labels: hacktoberfest-accepted

#111 updated index.html
  index.html
Labels: hacktoberfest-accepted

#112 added my profile card
  index.html
Labels: hacktoberfest-accepted

#118 Update index.html
  index.html
Labels: hacktoberfest-accepted

#113 Added my card
  index.html
Labels: hacktoberfest-accepted

#114 updated index.html
  index.html
Labels: hacktoberfest-accepted

#121 updated index.html
  index.html
Labels: hacktoberfest-accepted

#116 Update index.html
  index.html
Labels: hacktoberfest-accepted

#117 Add myself to the card
  index.html
Labels: hacktoberfest-accepted

#119 adding fawaz siddiqi
  index.html
Labels: hacktoberfest-accepted

#122 Update index.html
  index.html
Labels: hacktoberfest-accepted

#123 Updated index.html
  index.html
Labels: hacktoberfest-accepted

#125 Update index.html
  index.html
Labels: hacktoberfest-accepted

#126 Made the required changes
  index.html
Labels: hacktoberfest-accepted

#124 Update index.html
  index.html
Labels: hacktoberfest-accepted

#130 Update index.html
  index.html
Labels: hacktoberfest-accepted

#133 Update index.html
  index.html
Labels: hacktoberfest-accepted

#132 Profile Added
  index.html
Labels: hacktoberfest-accepted

#131 Update index.html
  index.html
Labels: hacktoberfest-accepted

#129 Update index.html
  index.html
Labels: hacktoberfest-accepted

#107 Updated index.html
  index.html
Labels: bug, hacktoberfest-accepted

#104 Update index.html
  index.html
Labels: hacktoberfest-accepted

#127 Update index.html
  index.html
Labels: hacktoberfest-accepted

#128 Update index.html
  index.html
Labels: hacktoberfest-accepted

#135 updated index.html
  index.html
Labels: hacktoberfest-accepted

#136 Update index.html
  index.html
Labels: hacktoberfest-accepted

#137 my details added
  index.html
Labels: hacktoberfest-accepted

#138 added my card
  index.html
Labels: hacktoberfest-accepted

#139 Update index.html
  index.html
Labels: hacktoberfest-accepted

#140 Update index.html by Aditya
  index.html
Labels: hacktoberfest-accepted

#141 Added my Github Profile
  index.html
Labels: hacktoberfest-accepted

#142 Added My Github Profile
  index.html
Labels: hacktoberfest-accepted

#143 Updated the index.html file by adding my details.
  index.html
Labels: hacktoberfest-accepted

#145 code added
  index.html
Labels: hacktoberfest-accepted

#146 added the necessary code block
  index.html
Labels: hacktoberfest-accepted

#147 Update index.html ✨
  index.html
Labels: hacktoberfest-accepted

#148 Updated the index.html file
  index.html
Labels: hacktoberfest-accepted

#149 Added my myself in
  index.html
Labels: hacktoberfest-accepted

#150 Update index.html
  index.html
Labels: hacktoberfest-accepted

#151 added my user details in
  index.html
Labels: hacktoberfest-accepted

#152 Update index.html
  index.html
Labels: hacktoberfest-accepted

#153 Add Amon card
  index.html
Labels: hacktoberfest-accepted

#154 Added Card for Aaryan Garg
  index.html
Labels: hacktoberfest-accepted

#155 updated the index.html file
  index.html
Labels: hacktoberfest-accepted

#156 Update Name
  index.html
Labels: hacktoberfest-accepted

#158 update card
  index.html
Labels: hacktoberfest-accepted

#159 Added the New user.
  index.html
Labels: hacktoberfest-accepted

#160 Updated index.html
  index.html
Labels: hacktoberfest-accepted

#162 add new card to index.html
  index.html
Labels: hacktoberfest-accepted

#163 feat(added my card)
  index.html
Labels: hacktoberfest-accepted

#164 Update index.html
  index.html
Labels: hacktoberfest-accepted

#165 Update index.html
  index.html
Labels: hacktoberfest-accepted

#166 index.html
  index.html
Labels: hacktoberfest-accepted

#168 Update index.html
  index.html
Labels: hacktoberfest-accepted

#169 Card has been Created
  index.html
Labels: hacktoberfest-accepted

#170 Added a card
  index.html
Labels: hacktoberfest-accepted

#171 new profile added
  index.html
Labels: hacktoberfest-accepted

#172 Update index.html
  index.html
Labels: hacktoberfest-accepted

#173 Added my profile
  index.html
Labels: hacktoberfest-accepted

#174 Updated index.html by Pratham Mittal
  index.html
Labels: hacktoberfest-accepted

#176 Add - Ramya Chinnadurai link
  index.html
Labels: hacktoberfest-accepted

#177 Update index.html
  index.html
Labels: hacktoberfest-accepted

#167 Added Own Card and Also spacing wherever necessary #Hacktoberfest-2021
  css/landing.css
  css/team.css
  index.html
Labels: enhancement, hacktoberfest-accepted

#178 Added my profile
  index.html
Labels: hacktoberfest-accepted

#179 Update index.html
  index.html
Labels: hacktoberfest-accepted

#180 Add Diptenu Sarkar link
  index.html
Labels: hacktoberfest-accepted

#181 Update index.html
  index.html
Labels: hacktoberfest-accepted

#182 Update index.html
  index.html
Labels: hacktoberfest-accepted
